In [1]:
import pandas as pd

In [2]:
dfs = pd.DataFrame([[0, 2, 3], [0, 4, 1], [10, 20, 30]], columns=['A', 'B', 'C'])

In [7]:
print(dfs.values)
print(dfs.columns)
print('At third row under col B: '+str(dfs.at[2,'B']))

[[ 0  2  3]
 [ 0  4  1]
 [10 20 30]]
Index(['A', 'B', 'C'], dtype='object')
At third row under col B: 20


In [14]:
df = pd.read_csv('../data/50_startups.csv')
df.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [12]:
#df.isna()
#df.dropna()
df2 = df[df['State']=='Florida']
df2.head(10)

R&D Spend  Administration  Marketing Spend    State     Profit
2   153441.51       101145.55        407934.54  Florida  191050.39
4   142107.34        91391.77        366168.42  Florida  166187.94
7   130298.13       145530.06        323876.68  Florida  155752.60
10  101913.08       110594.11        229160.95  Florida  146121.95
12   93863.75       127320.38        249839.44  Florida  141585.52
14  119943.24       156547.42        256512.92  Florida  132602.65
18   91749.16       114175.79        294919.57  Florida  124266.90
22   73994.56       122782.75        303319.26  Florida  110352.25
23   67532.53       105751.03        304768.73  Florida  108733.99
26   75328.87       144135.98        134050.07  Florida  105733.54

In [17]:
print ("Cal. company with R&D Spend over 100K")
df[(df['Administration'] > 100000) & (df['State'] == 'Florida' )]

Cal. company with R&D Spend over 100K


R&D Spend  Administration  Marketing Spend    State     Profit
2   153441.51       101145.55        407934.54  Florida  191050.39
7   130298.13       145530.06        323876.68  Florida  155752.60
10  101913.08       110594.11        229160.95  Florida  146121.95
12   93863.75       127320.38        249839.44  Florida  141585.52
14  119943.24       156547.42        256512.92  Florida  132602.65
18   91749.16       114175.79        294919.57  Florida  124266.90
22   73994.56       122782.75        303319.26  Florida  110352.25
23   67532.53       105751.03        304768.73  Florida  108733.99
26   75328.87       144135.98        134050.07  Florida  105733.54
28   66051.52       182645.56        118148.20  Florida  103282.38
30   61994.48       115641.28         91131.24  Florida   99937.59
33   55493.95       103057.49        214634.81  Florida   96778.92
36   28663.76       127056.21        201126.82  Florida   90708.19
46    1315.46       115816.21        297114.46  Florida   49490.75

In [22]:
import numpy as np
df['new col']=np.arange(50)
df.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit  new col
0  165349.20       136897.80        471784.10    New York  192261.83        0
1  162597.70       151377.59        443898.53  California  191792.06        1
2  153441.51       101145.55        407934.54     Florida  191050.39        2
3  144372.41       118671.85        383199.62    New York  182901.99        3
4  142107.34        91391.77        366168.42     Florida  166187.94        4
5  131876.90        99814.71        362861.36    New York  156991.12        5
6  134615.46       147198.87        127716.82  California  156122.51        6
7  130298.13       145530.06        323876.68     Florida  155752.60        7
8  120542.52       148718.95        311613.29    New York  152211.77        8
9  123334.88       108679.17        304981.62  California  149759.96        9

### create numpy array from Pandas dataframe

In [32]:
np_array = df.get_values()
np_array.shape

(50, 6)

### filter array based on rows/cols selection

In [29]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1:].values

In [30]:
X[:5]

array([[165349.2, 136897.8, 471784.1, 'New York', 192261.83],
       [162597.7, 151377.59, 443898.53, 'California', 191792.06],
       [153441.51, 101145.55, 407934.54, 'Florida', 191050.39],
       [144372.41, 118671.85, 383199.62, 'New York', 182901.99],
       [142107.34, 91391.77, 366168.42, 'Florida', 166187.94]],
      dtype=object)

In [31]:
y[:5]

array([[0],
       [1],
       [2],
       [3],
       [4]])