In [3]:
import numpy as np

In [4]:
arr1 = ["one", "two", "three", 3]
arr1

['one', 'two', 'three', 3]

In [10]:
arr = np.array([1, 2, 3, 4, 5, 'werwet'])
arr 

array(['1', '2', '3', '4', '5', 'werwet'], dtype='<U11')

In [6]:
z = np.zeros([2,3])
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
o = np.ones(25)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

### Arithmetic operation on Matrix

In [ ]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

In [ ]:
c = np.linspace(2.0, 3.0, num=10).reshape(-1, 2)
d = np.arange(14).reshape(2,-1)

# c * d is element wise operation and will give error
m = np.matmul(c, d) # this is classic matrix multiplication
m

# A basic neural network operation

W = np.random.randn(5, 4)
X = np.arange(20).reshape(4, -1)

A = np.dot(W, X)
A

### Broadcasting in Python

In [ ]:
# A scalar gets added to an array. Both are of entirely separate dimenssions

e = np.linspace(2, 10, num=10)
e + 4

# Two matrices of different sizes

M = np.ones((3, 3))
M + a

# Previously, we saw this
W = np.random.randn(5, 4) * 0.01
X = np.arange(12).reshape(4, 3)
A = np.dot(W, X)

# A different dimenssion vector
b = np.ones((1, 3)) # b = [1., 1., 1.,]
# Now vector b can be broadcasted to A
b + A # or A + b

In [ ]:
o = np.ones([5,5])
o

In [ ]:
e = np.identity(4)
e

In [ ]:
ls = np.linspace(2.0, 3.0, num=5, retstep=True)
ls

### Stacking

In [14]:
# column wise stack
np.column_stack(([2,1,2], [4,5,-1]))

array([[ 2,  4],
       [ 1,  5],
       [ 2, -1]])

In [15]:
a = np.array([1, 2, 3])
b = np.array([-3,-6,10])
# vertical stacking - specify a tuple - 
np.vstack((a,b))

array([[ 1,  2,  3],
       [-3, -6, 10]])

In [16]:
# horizontal stacking - specify a tuple - 
np.hstack((a,b))

array([ 1,  2,  3, -3, -6, 10])

### create sub-array / array spliting

In [31]:
x = np.arange(25).reshape(-1,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
# all rows and first 3 cols
x[:,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [37]:
# rows 1 to 3 and cols 2 to 4
x[:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [26]:
# all rows and all but last col
x[:,:-1]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [27]:
# all rows and last col
x[:,-1:]

array([[ 4],
       [ 9],
       [14],
       [19]])

### filter array

In [23]:
y = np.array([10,15,4,-3,11,17,22,])
fltr = y[y < 17]
fltr

array([10, 15,  4, -3, 11])