In [1]:
import numpy as np

### Find mean

In [16]:
dim = np.vstack(([2,1,2], [4,5,-1]))
dim

array([[ 2,  1,  2],
       [ 4,  5, -1]])

In [5]:
# calculate mean of second column 
np.mean(dim[:,1])

3.0

### Get subarray

In [14]:
x = np.arange(21).reshape(-1,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [12]:
# rows 1 to 3 and cols 2 and 3
x[:3,1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Implement matrix operations 

1. create a 4x3 matrix using numpy arange(-6,6,1) and reshape() functions, save to 'X'
2. create a 2X4 matrix using np.random.randn((2,4)) * 0.02, save to 'W'
3. multiple W.X using np.dot() and add '1' to each element, save to 'A'
4. Calculate tanh(A), save to Z 

In [47]:
np.random.seed(3)
X = np.arange(?).reshape(?)
X 

array([[-6, -5, -4],
       [-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [48]:
W = ?
W

array([[ 0.03577257,  0.0087302 ,  0.00192995, -0.03726985],
       [-0.00554776, -0.00709518, -0.00165483, -0.01254001]])

In [49]:
A = ?
A

array([[0.64736443, 0.65652729, 0.66569015],
       [1.01695208, 0.9901143 , 0.96327651]])

In [50]:
Z= ?
Z

array([[0.56989304, 0.5760477 , 0.58213772],
       [0.76862219, 0.75741106, 0.7457348 ]])